//===- ComputeVisitor.h ----------------------------------------------------===//
//
//                             The ONNC Project
//
// See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
#ifndef ONNC_IR_COMPUTE_VISITOR_H
#define ONNC_IR_COMPUTE_VISITOR_H

namespace onnc {

class Abs;
class Acos;
class Add;
class And;
class ArgMax;
class ArgMin;
class Asin;
class Atan;
class AveragePool;
class BatchNormalization;
class Cast;
class Ceil;
class Clip;
class Concat;
class Constant;
class Conv;
class ConvTranspose;
class Cos;
class DepthToSpace;
class Div;
class Dropout;
class Elu;
class Equal;
class Exp;
class Flatten;
class Floor;
class GRU;
class Gather;
class Gemm;
class GlobalAveragePool;
class GlobalLpPool;
class GlobalMaxPool;
class Greater;
class HardSigmoid;
class Hardmax;
class Identity;
class InstanceNormalization;
class LRN;
class LSTM;
class LeakyRelu;
class Less;
class Log;
class LogSoftmax;
class LpNormalization;
class LpPool;
class MatMul;
class Max;
class MaxPool;
class MaxRoiPool;
class Mean;
class Min;
class Mul;
class Neg;
class Not;
class Or;
class PRelu;
class Pad;
class Pow;
class RNN;
class RandomNormal;
class RandomNormalLike;
class RandomUniform;
class RandomUniformLike;
class Reciprocal;
class ReduceL1;
class ReduceL2;
class ReduceLogSum;
class ReduceLogSumExp;
class ReduceMax;
class ReduceMean;
class ReduceMin;
class ReduceProd;
class ReduceSum;
class ReduceSumSquare;
class Relu;
class Reshape;
class Selu;
class Shape;
class Sigmoid;
class Sin;
class Size;
class Slice;
class Softmax;
class Softplus;
class Softsign;
class SpaceToDepth;
class Split;
class Sqrt;
class Squeeze;
class Sub;
class Sum;
class Tan;
class Tanh;
class Tile;
class TopK;
class Transpose;
class Unsqueeze;
class Upsample;
class Xor;
class ATen;
class Affine;
class ConstantFill;
class Crop;
class FC;
class GRUUnit;
class GivenTensorFill;
class If;
class ImageScaler;
class Loop;
class LoopIndexTensor;
class MeanVarianceNormalization;
class ParametricSoftplus;
class Scale;
class ScaledTanh;
class ThresholdedRelu;
class Upsample;

/** \class ComputeVisitor
 */
class ComputeVisitor
{
public:
  virtual void visit(Abs& pAbs) = 0;
  virtual void visit(Acos& pAcos) = 0;
  virtual void visit(Add& pAdd) = 0;
  virtual void visit(And& pAnd) = 0;
  virtual void visit(ArgMax& pArgMax) = 0;
  virtual void visit(ArgMin& pArgMin) = 0;
  virtual void visit(Asin& pAsin) = 0;
  virtual void visit(Atan& pAtan) = 0;
  virtual void visit(AveragePool& pAveragePool) = 0;
  virtual void visit(BatchNormalization& pBatchNormalization) = 0;
  virtual void visit(Cast& pCast) = 0;
  virtual void visit(Ceil& pCeil) = 0;
  virtual void visit(Clip& pClip) = 0;
  virtual void visit(Concat& pConcat) = 0;
  virtual void visit(Constant& pConstant) = 0;
  virtual void visit(Conv& pConv) = 0;
  virtual void visit(ConvTranspose& pConvTranspose) = 0;
  virtual void visit(Cos& pCos) = 0;
  virtual void visit(DepthToSpace& pDepthToSpace) = 0;
  virtual void visit(Div& pDiv) = 0;
  virtual void visit(Dropout& pDropout) = 0;
  virtual void visit(Elu& pElu) = 0;
  virtual void visit(Equal& pEqual) = 0;
  virtual void visit(Exp& pExp) = 0;
  virtual void visit(Flatten& pFlatten) = 0;
  virtual void visit(Floor& pFloor) = 0;
  virtual void visit(GRU& pGRU) = 0;
  virtual void visit(Gather& pGather) = 0;
  virtual void visit(Gemm& pGemm) = 0;
  virtual void visit(GlobalAveragePool& pGlobalAveragePool) = 0;
  virtual void visit(GlobalLpPool& pGlobalLpPool) = 0;
  virtual void visit(GlobalMaxPool& pGlobalMaxPool) = 0;
  virtual void visit(Greater& pGreater) = 0;
  virtual void visit(HardSigmoid& pHardSigmoid) = 0;
  virtual void visit(Hardmax& pHardmax) = 0;
  virtual void visit(Identity& pIdentity) = 0;
  virtual void visit(InstanceNormalization& pInstanceNormalization) = 0;
  virtual void visit(LRN& pLRN) = 0;
  virtual void visit(LSTM& pLSTM) = 0;
  virtual void visit(LeakyRelu& pLeakyRelu) = 0;
  virtual void visit(Less& pLess) = 0;
  virtual void visit(Log& pLog) = 0;
  virtual void visit(LogSoftmax& pLogSoftmax) = 0;
  virtual void visit(LpNormalization& pLpNormalization) = 0;
  virtual void visit(LpPool& pLpPool) = 0;
  virtual void visit(MatMul& pMatMul) = 0;
  virtual void visit(Max& pMax) = 0;
  virtual void visit(MaxPool& pMaxPool) = 0;
  virtual void visit(MaxRoiPool& pMaxRoiPool) = 0;
  virtual void visit(Mean& pMean) = 0;
  virtual void visit(Min& pMin) = 0;
  virtual void visit(Mul& pMul) = 0;
  virtual void visit(Neg& pNeg) = 0;
  virtual void visit(Not& pNot) = 0;
  virtual void visit(Or& pOr) = 0;
  virtual void visit(PRelu& pPRelu) = 0;
  virtual void visit(Pad& pPad) = 0;
  virtual void visit(Pow& pPow) = 0;
  virtual void visit(RNN& pRNN) = 0;
  virtual void visit(RandomNormal& pRandomNormal) = 0;
  virtual void visit(RandomNormalLike& pRandomNormalLike) = 0;
  virtual void visit(RandomUniform& pRandomUniform) = 0;
  virtual void visit(RandomUniformLike& pRandomUniformLike) = 0;
  virtual void visit(Reciprocal& pReciprocal) = 0;
  virtual void visit(ReduceL1& pReduceL1) = 0;
  virtual void visit(ReduceL2& pReduceL2) = 0;
  virtual void visit(ReduceLogSum& pReduceLogSum) = 0;
  virtual void visit(ReduceLogSumExp& pReduceLogSumExp) = 0;
  virtual void visit(ReduceMax& pReduceMax) = 0;
  virtual void visit(ReduceMean& pReduceMean) = 0;
  virtual void visit(ReduceMin& pReduceMin) = 0;
  virtual void visit(ReduceProd& pReduceProd) = 0;
  virtual void visit(ReduceSum& pReduceSum) = 0;
  virtual void visit(ReduceSumSquare& pReduceSumSquare) = 0;
  virtual void visit(Relu& pRelu) = 0;
  virtual void visit(Reshape& pReshape) = 0;
  virtual void visit(Selu& pSelu) = 0;
  virtual void visit(Shape& pShape) = 0;
  virtual void visit(Sigmoid& pSigmoid) = 0;
  virtual void visit(Sin& pSin) = 0;
  virtual void visit(Size& pSize) = 0;
  virtual void visit(Slice& pSlice) = 0;
  virtual void visit(Softmax& pSoftmax) = 0;
  virtual void visit(Softplus& pSoftplus) = 0;
  virtual void visit(Softsign& pSoftsign) = 0;
  virtual void visit(SpaceToDepth& pSpaceToDepth) = 0;
  virtual void visit(Split& pSplit) = 0;
  virtual void visit(Sqrt& pSqrt) = 0;
  virtual void visit(Squeeze& pSqueeze) = 0;
  virtual void visit(Sub& pSub) = 0;
  virtual void visit(Sum& pSum) = 0;
  virtual void visit(Tan& pTan) = 0;
  virtual void visit(Tanh& pTanh) = 0;
  virtual void visit(Tile& pTile) = 0;
  virtual void visit(TopK& pTopK) = 0;
  virtual void visit(Transpose& pTranspose) = 0;
  virtual void visit(Unsqueeze& pUnsqueeze) = 0;
  virtual void visit(Upsample& pUpsample) = 0;
  virtual void visit(Xor& pXor) = 0;
  virtual void visit(ATen& pATen) = 0;
  virtual void visit(Affine& pAffine) = 0;
  virtual void visit(ConstantFill& pConstantFill) = 0;
  virtual void visit(Crop& pCrop) = 0;
  virtual void visit(FC& pFC) = 0;
  virtual void visit(GRUUnit& pGRUUnit) = 0;
  virtual void visit(GivenTensorFill& pGivenTensorFill) = 0;
  virtual void visit(If& pIf) = 0;
  virtual void visit(ImageScaler& pImageScaler) = 0;
  virtual void visit(Loop& pLoop) = 0;
  virtual void visit(LoopIndexTensor& pLoopIndexTensor) = 0;
  virtual void visit(MeanVarianceNormalization& pMeanVarianceNormalization) = 0;
  virtual void visit(ParametricSoftplus& pParametricSoftplus) = 0;
  virtual void visit(Scale& pScale) = 0;
  virtual void visit(ScaledTanh& pScaledTanh) = 0;
  virtual void visit(ThresholdedRelu& pThresholdedRelu) = 0;
  virtual void visit(Upsample& pUpsample) = 0;
};

} // namespace of onnc

#endif
