include(${CMAKE_CURRENT_LIST_DIR}/GetHostQuadruple.cmake)
macro(check_canonical_system)
    if (UNIX)
        set(ONNC_ON_UNIX 1)
    endif()
    if (WIN32)
        set(ONNC_ON_WIN32 1)
    endif()
    if (APPLE)
        set(ONNC_ON_APPLE 1)
    endif()
    if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        set(ONNC_ON_LINUX 1)
    endif()
    get_host_quadruple(ONNC_DEFAULT_TARGET_QUADRUPLE)
    #set(ONNC_ON_BSD 1)
endmacro()
