
function(enum_onnc_targets)
    option(TARGET_ALL "Build all targets" OFF)

    set(ONNC_TARGET_PLATFORMS "")
    set(ONNC_TARGET_BACKENDS "")
    macro(add_target name default_value)
        string(TOUPPER ${name} op_name)
        if (TARGET_ALL)
            set(TARGET_${op_name} ON               CACHE BOOL "Build ${name}" FORCE)
        else()
            set(TARGET_${op_name} ${default_value} CACHE BOOL "Build ${name}")
        endif()
        set(ENABLE_${op_name}_TARGET ${TARGET_${op_name}} PARENT_SCOPE)
        if (TARGET_${op_name})
            set(ONNC_TARGET_PLATFORMS "${ONNC_TARGET_PLATFORMS} ONNC_PLATFORM(${op_name})")
            set(ONNC_TARGET_BACKENDS "${ONNC_TARGET_BACKENDS} ONNC_BACKEND(${op_name})")
        endif()
    endmacro()
    add_target(x86 ON)
    add_target(tg OFF)
    add_target(sophon OFF)
    set(ONNC_TARGET_PLATFORMS "${ONNC_TARGET_PLATFORMS}" PARENT_SCOPE)
    set(ONNC_TARGET_BACKENDS "${ONNC_TARGET_BACKENDS}" PARENT_SCOPE)

endfunction()
