
function(tg_test)
    cmake_parse_arguments(OPT "" "ASM_NAME;MARCH" "ONNX2TG_ARGS" ${ARGN})
    get_filename_component(name ${OPT_ASM_NAME} NAME_WE)
    get_filename_component(dir ${OPT_ASM_NAME} DIRECTORY)
    set(onnx_name ${CMAKE_CURRENT_BINARY_DIR}/${dir}/${name}.onnx)
    set(asm_name ${CMAKE_CURRENT_SOURCE_DIR}/${OPT_ASM_NAME})
    set(log_name ${CMAKE_CURRENT_BINARY_DIR}/${dir}/${name}.log)
    configure_file(${ONNC_SOURCE_DIR}/lib/Target/TG/test/template.sh test-${name}.sh)
    add_test(NAME tg_test_${name} COMMAND test-${name}.sh $<TARGET_FILE:onnx-as> $<TARGET_FILE:onnx2tg>)
endfunction()
